name: CI

on: push

jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Used golang 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.2
    - run: go mod download
    - run: go mod tidy
    - run: go mod graph
    - run: make check
    - run: make tests
