name: CI

on: push

jobs:
  lint-and-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: vtemian/pgtest
        env:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: password
        ports:
            - 5432:5432
        options: >-
         --health-cmd pg_isready
         --health-interval 10s
         --health-timeout 5s
         --health-retries 5
      api:
        image: vtemian/apitest
        env:
            VAULT_ADDR: http://vault:8200
            VAULT_TOKEN: 8fb95528-57c6-422e-9722-d2147bcba8ed
            PSQL_USER: root
            PSQL_PASSWORD: password
            PSQL_HOST: postgres
            SQL_PORT: 5432
            STACK_NAME: f3-interview-accountapi
            DATABASE-HOST: localhost
            DATABASE-SSL-MODE: disable
            DATABASE-USERNAME: interview_accountapi_user
            DATABASE-PASSWORD: 123
        ports:
            - 8080:8080
      vault:
        image: vault:0.9.3
        ports:
            - 8200:8200
        env:
            SKIP_SETCAP: 1
            VAULT_DEV_ROOT_TOKEN_ID: 8fb95528-57c6-422e-9722-d2147bcba8ed

    steps:
    - uses: actions/checkout@v2
    - name: Used golang 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.2
    - run: go mod download
    - run: go get github.com/onsi/ginkgo/ginkgo
    - run: make check
    - run: make tests
      env:
          TEST_API_HOST: http://localhost:8080
    - name: Dump docker logs on failure
      if: failure()
      uses: jwalton/gh-docker-logs@v1
