name: CI

on: push

jobs:
  lint-and-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Used golang 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - run: go mod download
      env:
        GO111MODULE: on
    - run: go list -m
    - run: make check
    - run: make tests
